import{a as p,S as u,i as n}from"./assets/vendor-1AYLTIiv.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const f="50779054-370421c42d6be36ab94d11a5f",y="https://pixabay.com/api/";function d(a){const s={key:f,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0};return p.get(y,{params:s}).then(t=>{if(t.data.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return t.data})}const m=new u(".gallery a",{captionsData:"alt",cartionDelay:250}),l=document.querySelector(".gallery"),c=document.querySelector(".loader");function g(a){const s=a.map(t=>`<li class="gallery-item">
        <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" class="image">
        </a>
        <div class="description">
        <p class="text">Likes<span class="span">${t.likes}</span></p>
        <p class="text">Views<span class="span">${t.views}</span></p>
        <p class="text">Comments<span class="span">${t.comments}</span></p>
        <p class="text">Downloads<span class="span">${t.downloads}</span></p>
        </div>
        </li>`).join("");l.insertAdjacentHTML("beforeend",s),m.refresh()}function h(){l.innerHTML=""}function L(){c.style.display="block"}function w(){c.style.display="none"}const b=document.querySelector(".form");b.addEventListener("submit",a=>{a.preventDefault();const s=a.target.elements["search-text"],t=s?s.value.trim():"";if(!t){n.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}h(),L(),d(t).then(o=>{if(!o||!Array.isArray(o.hits)){n.error({title:"Error",message:"Invalid API response. Please try again later.",position:"topRight"});return}const e=o.hits;e.length===0?n.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):g(e)}).catch(o=>{console.error("Error fetchin images:",o),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}).finally(()=>{w()})});
//# sourceMappingURL=index.js.map
