import{a as p,S as u,i}from"./assets/vendor-1AYLTIiv.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const d="50779054-370421c42d6be36ab94d11a5f",f="https://pixabay.com/api/";function m(a){const s={key:d,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0};return p.get(f,{params:s}).then(e=>{if(e.data.hits.length===0)throw new Error(`Sorry, there are no images matching your search query. Please try again!
`);return e.data})}const y=new u(".gallery a",{captionsData:"alt",cartionDelay:250}),l=document.querySelector(".gallery"),c=document.querySelector(".loader");function g(a){const s=a.map(e=>`<li class="gallery-item">
        <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" class="image">
        </a>
        <div class="description">
        <p class="text">Likes<span class="span">${e.likes}</span></p>
        <p class="text">Views<span class="span">${e.views}</span></p>
        <p class="text">Comments<span class="span">${e.comments}</span></p>
        <p class="text">Downloads<span class="span">${e.downloads}</span></p>
        </div>
        </li>`).join("");l.insertAdjacentHTML("beforeend",s),y.refresh()}function h(){l.innerHTML=""}function w(){c.style.display="block"}function L(){c.style.display="none"}const b=document.querySelector(".form");document.querySelector(".gallery");b.addEventListener("submit",a=>{a.preventDefault();const s=a.target.elements["search-text"].value.trim();if(!s){i.warning({title:"warning",message:"Please enter a search term",position:"topRight"});return}h(),w(),m(s).then(e=>{const{hits:o}=e;o.lenght===0?i.info({title:"Info",message:"Sorry, there are no images matchinSorry, there are no images matching your search query. Please try again!",position:"topRight"}):g(o)}).catch(e=>{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}).finnaly(()=>{L()})});
//# sourceMappingURL=index.js.map
